// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJSYFqBKr5Zml__Ca2TaroF8Mxm0A4sQ',
    appId: '1:58985854033:web:0d2a9b8805c5408d4f3470',
    messagingSenderId: '58985854033',
    projectId: 'bookingfirebase-8f23c',
    authDomain: 'bookingfirebase-8f23c.firebaseapp.com',
    storageBucket: 'bookingfirebase-8f23c.appspot.com',
    measurementId: 'G-EQNK5H1L61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGqUKIHlvyeS-jjYWelvFsz0GurKLZec',
    appId: '1:58985854033:android:d9bcb48bd876b91e4f3470',
    messagingSenderId: '58985854033',
    projectId: 'bookingfirebase-8f23c',
    storageBucket: 'bookingfirebase-8f23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3Iy9b8Mx7FXvWi_cUfYQ86FVdpxVyek',
    appId: '1:58985854033:ios:5635d939457378574f3470',
    messagingSenderId: '58985854033',
    projectId: 'bookingfirebase-8f23c',
    storageBucket: 'bookingfirebase-8f23c.appspot.com',
    iosBundleId: 'com.example.onlineSeatBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt3Iy9b8Mx7FXvWi_cUfYQ86FVdpxVyek',
    appId: '1:58985854033:ios:75c50b13901b45cd4f3470',
    messagingSenderId: '58985854033',
    projectId: 'bookingfirebase-8f23c',
    storageBucket: 'bookingfirebase-8f23c.appspot.com',
    iosBundleId: 'com.example.onlineSeatBookingApp.RunnerTests',
  );
}
